### ISSUE TITLE
(Custom) Splits and DiffDock's weights

### ISSUE THREAD

**Issue by Jakub-11** [plinder-org/plinder#72]
Hi,

Thank you very much for this very important work. I see that in some aspects it is still in progress, but I would like to nevertheless ask a few questions:

1. The docs/examples/5_dataset_and_loader.ipynb notebook implies existence of the split_parquet_path argument passed to the PlinderDataset, but it seems to be currently missing. Will it be added?
2. Can we get some comments on the logic/idea behind splits available in v2:
![image](https://github.com/user-attachments/assets/a156194e-fba4-43cf-80c0-8c6cddf31ca6)
Naturally there are many ways to split the data according to the task at hand, so it would be great to hear some insights from the frontrunners of splitting PL systems.
3. Will it be possible to create custom splits with the method described in the preprint?
4. Would it be possible to share the weights of the retrained DiffDock which scores you reported in the preprint?

I would be very grateful for all the answers and comments, thank you.

Best,
Jakub Kopko

**Comment by yusuf1759** [comment]
> 1. The docs/examples/5_dataset_and_loader.ipynb notebook implies existence of the split_parquet_path argument passed to the PlinderDataset, but it seems to be currently missing. Will it be added?

My guess here is you are using a old version of the code, initializing `PlinderDataset` with `split_parquet_path` was deprecated recently. I suggest you pull `main` again and everything should work fine.

> 2. Can we get some comments on the logic/idea behind splits available in v2.

The exact split configuration that was used for v2 is provided split.yaml including the descriptions:
https://plinder-org.github.io/plinder/dataset.html#splits-splits
The key change was to switch from pocket_lddt=50 graph in v1 to a multi-graph using pli_unique_qcov=30 and protein_seqsim_weighted_sum=30 - to ensure that split is robustly deleaked for protein similarity (not only pocket) due to intended use in cofolding predictions (simultaneously predicting protein fold and ligand binding pose).
We also reduced the test and val test from 4k to more managable size of just under 1k. Finally, we took a careful approach to boost the ligand diversity in test set by deduplicating ligand/protein systems in the final set.

> 3. Will it be possible to create custom splits with the method described in the preprint?

Yes, the code to do so can be found [here](https://github.com/plinder-org/plinder/blob/main/src/plinder/data/splits.py)

> 4. Would it be possible to share the weights of the retrained DiffDock which scores you reported in the preprint?

For now, no. The model was trained with NVIDIA BioNemo which is a proprietary platform.
If you have more questions, please checkout out [Discord](https://discord.gg/PNJttT2R) channel.

**Comment by Ninjani** [comment]
@Jakub-11 Also FYI working on some docs/tutorial for custom splitting, please reach out on the Discord if you'd like help with that!

**Comment by Jakub-11** [comment]
Thank you very much for an exhaustive answer, it is truly appreciated! As is the work of the whole team on PLINDER.
@Ninjani I would be happy to help! But the Discord invite Yusuf posted seems to be expired, can you help with that?

**Comment by Ninjani** [comment]
@Jakub-11 Sorry about that, [this](https://discord.gg/KgUdMn7TuS) should work
