### ISSUE TITLE
Wrong source links from documentation

### ISSUE THREAD

**Issue by Endyff** [plinder-org/plinder#73]
In the Python API documentation, e.g. [plinder.core.scores.query_ligand_similarity](https://plinder-org.github.io/plinder/api/scores/plinder.core.scores.query_ligand_similarity.html) as well as the others, the link for the [source] is https://github.com/plinder-org/plinder/blob/v0.1.dev1+g1a8230e/src/plinder/core/scores/ligand.py#L18-L54 is to non-existing tag _v0.1.dev1+g1a8230e_ so we get _404 - page not found_ error. The correct url should be https://github.com/plinder-org/plinder/blob/main/src/plinder/core/scores/ligand.py#L18-L54 - linking to main.

**Comment by padix-key** [comment]
Hi, thanks for the report. When you point the source link to the `main` branch, you can get the problem that the repository and the doc get out of sync: If after the documentation release lines of code are added or removed in `main`, the highlighted lines do not correspond to the range of the class/function anymore. Hence, the link points the code with the same version the docs were build for.

But still you are correct: The URL is wrong, it should point to https://github.com/plinder-org/plinder/blob/v0.2.10/src/plinder/core/scores/ligand.py#L18-L54.
The reason is the git tag: To generate the URLs `plinder.__version__` is accessed which again uses the git tag when the package is built.

I suspect the CI is the culprit here. The `docs` workflow runs in parallel to the `main` workflow, so `docs` does not use the new git tag, as it is generated in the `main` workflow. Instead it presumably uses the autogenerated version from `setuptools-scm`, in this case `v0.1.dev1+g1a8230e`.

I will create a PR and check if my theory is correct :wink:
