### ISSUE TITLE
Suggestion: Better notification message for `plinder_download` when PLINDER_OFFLINE is set

### ISSUE THREAD

**Issue by rachitk** [plinder-org/plinder#75]
Hi, 

Thank you so much for developing this incredible resource! I'll be using it extensively for some of my future work.

This is admittedly just me mostly having overlooked my own configuration, so feel free to disregard this suggestion.

I downloaded PLINDER to use it offline by using the `plinder_download` command-line option, but it seems the download only partially completed (unknown to me). Proceeding under the assumption that the download had finished, I set `PLINDER_OFFLINE` and tried to use a few of the imports in my Python code, eventually hitting an error when only partially-downloaded files were found or missing.

I tried running `plinder_download` again and saw that it was failing to sync (just seemingly skipping all the steps by saying that everything succeeded in 0.00s). This occurred even after I set `PLINDER_OFFLINE` to false (not realizing that the check is just if the variable is set at all). 

Maybe check at the beginning of `plinder_download` if `PLINDER_OFFLINE` is set to any value, and if so, possibly warn the user that they may want to unset the variable if they want to download files? Or maybe add an option to ignore the variable and redownload anyways?

**Comment by OleinikovasV** [comment]
Thank you, @rachitk , we explain this detail for the users here and in our tutorial:
https://plinder-org.github.io/plinder/examples/1_download.html#
If a user would like to avoid this issue - it is possible to make the check for environment variables and unset them if they are not set to "true" or other preferred label.

This issue seems to be good to be closed :)

For further discussions or suggestions - feel free to join the user discord server: https://discord.gg/KgUdMn7TuS
